# Generated by Django 5.2.3 on 2025-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_snippet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
