# Generated by Django 5.2.3 on 2025-09-03 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['name', 'lang']},
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['name', 'lang'], name='MainApp_sni_name_48c470_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['user', 'name', 'lang'], name='MainApp_sni_user_id_2c247a_idx'),
        ),
    ]
