# Generated by Django 5.2.3 on 2025-09-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_notification_mainapp_not_recipie_7c69f4_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='MainApp_not_recipie_7c69f4_idx',
        ),
    ]
